title: somebody712 | Portfolio
description: somebody712의 활동, 경력, 프로젝트 포트폴리오.
lang: ko-KR
url: "https://somebody712.github.io"
baseurl: ""
timezone: Asia/Seoul
permalink: /:year/:month/:day/:title/
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
excerpt_separator: "<!--more-->"
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .github
  - _posts
  - categories
  - archive.md
  - about.md
  - feed.xml
